spring.application.name=artgal
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/art_gal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=Nguyen123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server Configuration
server.port=8088

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example.art_gal=DEBUG

# JWT configuration
app.jwtSecret=your_jwt_secret_key
app.jwtExpirationMs=86400000